server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1050592416253-mgsakt8ut4uu07q1oddfp9rg6nco7iuh.apps.googleusercontent.com
            client-secret: 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
            scope: 
              - email
              - profile

jwt:
  secret: your-jwt-secret-key-very-secure
  expiration: 86400000  # 24 horas en milisegundos
